import type { Node, Weight, OpNode, OpKind } from "../types";
import { denseNodes, sparseNodes, layerShard } from "./data";
import { CODE_BY_ID, QKV_INDEX_PROJECTION_SECTIONS, QKV_INDEX_PROJECTION_SYMBOLS } from "./evidence";
import { LATEX_BY_ID } from "./formulas";
import { VLLM_COMMIT, CODE_URL, RUNNER_URL, ACTIVATION_URL, VLLM_INDEXER_URL, NORM_FORWARD_URL } from "./sources";

const cloneOp = (base: Node, values: Partial<OpNode> & { id: string; kind: OpKind; title: string }): OpNode => {
  const detail=CODE_BY_ID[values.id];
  return { ...base, ...values, latex:values.latex??LATEX_BY_ID[values.id], codeSections:values.codeSections??detail?.sections, codeSymbols:values.codeSymbols??detail?.symbols };
};
export const pinSource = (url: string) => url.replace("/blob/main/", `/blob/${VLLM_COMMIT}/`);

export function denseGraph(layer: number): Record<string, OpNode> {
  const [norm, qkv, attn, out, mlp] = denseNodes(layer);
  const shard = layerShard(layer);
  const postNorm: Weight = { key: `language_model.model.layers.${layer}.post_attention_layernorm.weight`, shape: "[6144]", dtype: "BF16", shard, params: "6,144" };
  return {
    input: cloneOp(norm,{id:"d-input",kind:"io",title:"Hidden states",kicker:`L${layer} INPUT`,input:"Xₗ",inputShape:"[B,S,6144]",output:"residual + working copy",outputShape:"2 × [B,S,6144]",weights:[],formula:"residual ← Xₗ; working ← Xₗ"}),
    position: cloneOp(attn,{id:"d-position",kind:"route",title:"Build Position IDs",kicker:"vLLM RUNTIME I/O",input:"num_computed_tokens + query offsets",inputShape:"[B] + [Nq]",output:"positions",outputShape:"[Nq]",formula:"position(req,i)=num_computed_tokens[req]+i",formulaNote:"positions 不是模型权重，也不是在 Attention 内凭空产生；由 vLLM runner 根据每个请求已计算 token 数和本轮 query 偏移生成。",source:"gpu_model_runner.py · _prepare_inputs",sourceUrl:RUNNER_URL,weights:[]}),
    attnmeta: cloneOp(attn,{id:"d-attnmeta",kind:"mask",title:"Build Attention Metadata",kicker:"vLLM RUNTIME I/O",input:"query_start_loc, seq_lens, causal=True",inputShape:"[B+1] · [B] · bool",output:"implicit causal / padding layout",outputShape:"backend metadata; 非稠密 [S,T]",formula:"valid(req,q,k)=(k<seq_len[req]) ∧ (k≤context_len[req]+q)",formulaNote:"优化推理中通常不会真的构造 [S,T] mask；causal、query_start_loc 与 seq_lens 被后端内核直接消费。",source:"gpu_model_runner.py · CommonAttentionMetadata",sourceUrl:RUNNER_URL,weights:[]}),
    slots: cloneOp(attn,{id:"d-slots",kind:"route",title:"Resolve KV Slots",kicker:"vLLM RUNTIME I/O",input:"positions + block_table",inputShape:"[Nq] + [B,Nblocks]",output:"slot_mapping + block_table",outputShape:"[Nq] + [B,Nblocks]",formula:"slot=block_table[req,⌊position/block_size⌋]·block_size+(position mod block_size)",formulaNote:"slot_mapping 决定新 K/V 写到哪个物理槽；block_table 决定 Attention 从哪些物理 pages 读取。",source:"gpu_model_runner.py · compute_slot_mapping",sourceUrl:RUNNER_URL,weights:[]}),
    norm: cloneOp(norm,{id:"d-norm",kind:"norm",title:"Gemma RMSNorm",source:"nvidia/model.py · MiniMAXGemmaRMSNorm.forward · L130–142",sourceUrl:NORM_FORWARD_URL}),
    qkv: cloneOp(qkv,{id:"d-qkv",kind:"linear",title:"QKV Projection"}),
    split: cloneOp(qkv,{id:"d-split",kind:"split",title:"Split Q / K / V",input:"packed qkv",inputShape:"[B,S,9216]",output:"Q · K · V",outputShape:"8192 · 512 · 512",formula:"split(qkv,[8192,512,512],dim=-1)",formulaNote:"checkpoint 中三块矩阵分离；vLLM 运行时一次 GEMM 后切分。",weights:[]}),
    qnorm: cloneOp(attn,{id:"d-qnorm",kind:"norm",title:"Q Gemma RMSNorm · per-head",summary:"对每个 Q head 的 128 维向量独立执行 Gemma 风格 RMSNorm。",input:"Q",inputShape:"[B,64,S,128]",output:"Q̃",outputShape:"[B,64,S,128]",formula:"Q̃ₕ,ᵢ=Qₕ,ᵢ/√((1/Dₕ)ΣⱼQₕ,ⱼ²+ε)·(1+γQ,ᵢ)",formulaNote:"归一化轴仅为 head_dim=128；同一组 [128] q_norm.weight 应用于各个 Q head。",runtime:"fused_minimax_m3_qknorm_rope_kv_insert · Q norm stage",weights:attn.weights.filter(w=>w.key.includes("q_norm"))}),
    knorm: cloneOp(attn,{id:"d-knorm",kind:"norm",title:"K Gemma RMSNorm · per-head",summary:"对每个 K head 的 128 维向量独立执行 Gemma 风格 RMSNorm。",input:"K",inputShape:"[B,4,T,128]",output:"K̃",outputShape:"[B,4,T,128]",formula:"K̃ₕ,ᵢ=Kₕ,ᵢ/√((1/Dₕ)ΣⱼKₕ,ⱼ²+ε)·(1+γK,ᵢ)",formulaNote:"归一化轴仅为 head_dim=128；同一组 [128] k_norm.weight 应用于各个 K head。",runtime:"fused_minimax_m3_qknorm_rope_kv_insert · K norm stage",weights:attn.weights.filter(w=>w.key.includes("k_norm"))}),
    ropeq: cloneOp(attn,{id:"d-ropeq",kind:"rope",title:"Partial RoPE (Q)",summary:"仅对每个 Q head 的前 64/128 维应用 RoPE，后 64 维保持不变。",input:"Q̃ + positions",inputShape:"[B,64,S,128] + [S]",output:"Qᵣ",outputShape:"[B,64,S,128]",formula:"split Q̃ into Qrot(64) and Qpass(64); Qᵣ=concat(RoPE(Qrot,p),Qpass)",formulaNote:"先把每个 128 维 Q head 拆成两个 64 维分段。Qrot 使用 token 位置 p 做旋转，Qpass 不变，最后按原顺序拼回 128 维。",runtime:"fused_minimax_m3_qknorm_rope_kv_insert · Q partial RoPE stage",weights:[]}),
    ropek: cloneOp(attn,{id:"d-ropek",kind:"rope",title:"Partial RoPE (K)",summary:"仅对每个 K head 的前 64/128 维应用 RoPE，后 64 维保持不变。",input:"K̃ + positions",inputShape:"[B,4,T,128] + [T]",output:"Kᵣ",outputShape:"[B,4,T,128]",formula:"split K̃ into Krot(64) and Kpass(64); Kᵣ=concat(RoPE(Krot,p),Kpass)",formulaNote:"先把每个 128 维 K head 拆成两个 64 维分段。Krot 使用 token 位置 p 做旋转，Kpass 不变，最后按原顺序拼回 128 维。",runtime:"fused_minimax_m3_qknorm_rope_kv_insert · K partial RoPE stage",weights:[]}),
    cache: cloneOp(attn,{id:"d-cache",kind:"cache",title:"Paged KV Cache",summary:"L0–L2 的 Full GQA 从 Paged KV Cache 读取全部因果可见的历史与当前 K/V。",input:"Kᵣ,V + block table",inputShape:"[T,4,128] ×2",output:"visible K,V",outputShape:"[B,4,T,128] ×2",formula:"slot = block_table[seq, logical_block] + offset",formulaNote:"“全部可见”不包括未来 token 或 padding；block table 决定逻辑 KV 位置对应的物理 page。",runtime:"Attention backend · full causal Paged KV",weights:[]}),
    qk: cloneOp(attn,{id:"d-qk",kind:"matmul",title:"Q × Kᵀ",input:"Qᵣ,Kᵣ",inputShape:"[B,64/TP,S,128] · [B,max(1,4/TP),T,128]",output:"local scores",outputShape:"[B,64/TP,S,T]",formula:"A=QᵣKᵣᵀ",formulaNote:"单个 TP rank 只计算 64/TP 个 query heads；KV heads 为 max(1,4/TP)，当 TP>4 时按 vLLM 规则复制。",weights:[]}),
    scale: cloneOp(attn,{id:"d-scale",kind:"scale",title:"Scale 1/√128",input:"A",inputShape:"[B,64/TP,S,T]",output:"scaled scores",outputShape:"[B,64/TP,S,T]",formula:"A←A/√128",weights:[]}),
    mask: cloneOp(attn,{id:"d-mask",kind:"mask",title:"Apply Causal / Pad Bounds",input:"scores + attention metadata",inputShape:"[B,64/TP,S,T] + runtime metadata",output:"masked scores",outputShape:"[B,64/TP,S,T]",formula:"Aᵢⱼ←valid(i,j) ? Aᵢⱼ : −∞",formulaNote:"图中把 mask 画成逻辑算子；vLLM 后端实际以 causal、seq_lens 和 query_start_loc 实现，不物化完整 mask 矩阵。head 维为单 TP rank 的 64/TP。",weights:[]}),
    softmax: cloneOp(attn,{id:"d-softmax",kind:"softmax",title:"Softmax",input:"masked scores",inputShape:"[B,64/TP,S,T]",output:"attention prob",outputShape:"[B,64/TP,S,T]",formula:"P=softmax(A,dim=-1)",weights:[]}),
    pv: cloneOp(attn,{id:"d-pv",kind:"matmul",title:"P × V",input:"P,V",inputShape:"[B,64/TP,S,T] · [B,max(1,4/TP),T,128]",output:"local heads",outputShape:"[B,S,8192/TP]",formula:"Oₕ=PₕV⌊h/16⌋",formulaNote:"P × V 在每个 TP rank 上独立计算，得到 (64/TP)×128=8192/TP 的局部 attention 宽度，再交给 RowParallel O Projection。",weights:[]}),
    oproj: cloneOp(out,{id:"d-oproj",kind:"linear",title:"O Projection"}),
    add1: cloneOp(out,{id:"d-add1",kind:"add",kicker:"DECODER LAYER · ATTENTION RESIDUAL",title:"Attention Residual Merge",summary:"在 Decoder Layer 内把 Attention 分支 Yattn 加入 residual stream Xₗ，得到更新后的 U；图中将 fused add 与紧随其后的 post-norm 分开表达。",input:"Xₗ + Yattn",inputShape:"2 × [B,S,6144]",output:"U · updated residual stream",outputShape:"[B,S,6144]",formula:"U=Xₗ+Yattn",formulaNote:"实际调用位于 DecoderLayer.forward L773：fused kernel 先执行 residual += hidden_states，再对更新后的 residual 执行 post-attention Gemma RMSNorm。",runtime:"fused_allreduce_gemma_rms_norm · attention residual",source:"nvidia/model.py · MiniMaxM3DecoderLayer.forward · L773–775",sourceUrl:`${CODE_URL}#L773-L775`,weights:[]}),
    postnorm: cloneOp(norm,{id:"d-postnorm",kind:"norm",title:"Post-attn Gemma RMSNorm",summary:"输入 U 已由上游 Add 节点计算完成；此节点只执行 Gemma RMSNorm(U)，输出唯一的 Û 作为 FFN 输入。",formulaNote:"U 是上游 Add 的单一输出；本节点只计算 RMS(U) 与 (1+γpost) 缩放，不重复执行 residual add。",input:"U",inputShape:"[B,S,6144]",output:"Û",outputShape:"[B,S,6144]",source:"nvidia/model.py · MiniMAXGemmaRMSNorm.forward · L130–142",sourceUrl:NORM_FORWARD_URL,weights:[postNorm]}),
    gateup: cloneOp(mlp,{id:"d-gateup",kind:"linear",kicker:"DENSE FFN · H=6144 · H_dense=12288",title:"Gate + Up Projection",summary:"MergedColumnParallelLinear 让每个 TP rank 读取完整 Û，并分别计算局部 gate/up 投影；这里只做线性 GEMM。",input:"Û",inputShape:"[B,S,6144]",output:"packed gate_up (TP-local)",outputShape:"[B,S,24576/TP]",formulaNote:"Wgate⁽ʳ⁾ 与 Wup⁽ʳ⁾ 都沿输出维切分；本节点不执行 Split、clamp、SiLU 或逐元素乘。",runtime:"MergedColumnParallelLinear · gate_up_proj",weights:mlp.weights.filter(w=>!w.key.includes("down_proj"))}),
    gatesplit: cloneOp(mlp,{id:"d-gatesplit",kind:"split",kicker:"DENSE FFN · TP-LOCAL SPLIT",title:"Split Gate / Up",summary:"把当前 TP rank 的 packed gate_up 沿最后一维等分为 G⁽ʳ⁾ 和 U⁽ʳ⁾；不含权重，也不改变数值。",input:"packed gate_up (TP-local)",inputShape:"[B,S,24576/TP]",output:"G⁽ʳ⁾ · U⁽ʳ⁾",outputShape:"2 × [B,S,12288/TP]",formula:"(G⁽ʳ⁾,U⁽ʳ⁾)=split(gate_up⁽ʳ⁾,2,dim=-1)",formulaNote:"本节点只切分 view：前 H_dense/TP 个通道是 gate，后 H_dense/TP 个通道是 up；clamp 与 sigmoid 属于下一 SwiGLU-OAI 节点。",runtime:"SiluAndMulWithClamp · fused input slicing",source:"activation.py · SiluAndMulWithClamp.forward_native",sourceUrl:`${ACTIVATION_URL}#L214-L218`,weights:[]}),
    swiglu: cloneOp(mlp,{id:"d-swiglu",kind:"activation",kicker:"DENSE FFN · TP-LOCAL ACTIVATION",title:"SwiGLU-OAI",summary:"对当前 TP rank 的 G⁽ʳ⁾/U⁽ʳ⁾ 分片执行 gate 上界截断、up 双边截断、sigmoid、+β 与逐元素乘；不执行线性投影。",input:"G⁽ʳ⁾,U⁽ʳ⁾",inputShape:"2 × [B,S,12288/TP]",output:"Z⁽ʳ⁾",outputShape:"[B,S,12288/TP]",formulaNote:"forward_native 先以 c=7 截断两个分支，再计算 Ḡ⁽ʳ⁾⊙σ(αḠ⁽ʳ⁾)⊙(Ū⁽ʳ⁾+β)；α=1.702，β=1.0。",runtime:"vLLM: SiluAndMulWithClamp · layout: swigluoai_uninterleave",source:"activation.py · SiluAndMulWithClamp.forward_native · L214–218",sourceUrl:`${ACTIVATION_URL}#L214-L218`,weights:[]}),
    down: cloneOp(mlp,{id:"d-down",kind:"linear",kicker:"DENSE FFN · ROW PARALLEL · H=6144",title:"Down Projection",summary:"RowParallelLinear 消费每个 TP rank 的局部 activated 分片，将 H_dense/TP 投回 H，并归并各 rank 的部分结果。",input:"activated⁽ʳ⁾",inputShape:"[B,S,12288/TP]",output:"Yffn",outputShape:"[B,S,6144]",formulaNote:"本节点只执行 down projection；输入宽度为 H_dense/TP，输出隐藏宽度 H=6144。",weights:mlp.weights.filter(w=>w.key.includes("down_proj"))}),
    add2: cloneOp(mlp,{id:"d-add2",kind:"add",kicker:"DECODER LAYER · FFN RESIDUAL",title:"Decoder Layer Residual Merge",summary:"在 Decoder Layer 边界把 Dense FFN 分支 Yffn 与 residual stream U 逻辑合并，得到 Xₗ₊₁；该 merge 延迟融合到下一层 input RMSNorm。",input:"U + Yffn",inputShape:"2 × [B,S,6144]",output:"Xₗ₊₁ · logical next-layer input",outputShape:"[B,S,6144]",formula:"Xₗ₊₁=U+Yffn",formulaNote:"当前层 L776–778 返回 Yffn 与 U 两条独立流；下一 Decoder Layer 在 L758–767 的 fused input RMSNorm 中执行实际 add。",runtime:"MiniMaxM3DecoderLayer boundary · deferred residual merge",source:"nvidia/model.py · MiniMaxM3DecoderLayer.forward · L758–778",sourceUrl:`${CODE_URL}#L758-L778`,weights:[]}),
  };
}

export function sparseGraph(layer: number): Record<string, OpNode> {
  const [packed,indexer,topk,attn,router,experts,shared,combine]=sparseNodes(layer);
  const normBase=denseNodes(layer)[0];
  const shard=layerShard(layer);
  const inputNorm: Weight={key:`language_model.model.layers.${layer}.input_layernorm.weight`,shape:"[6144]",dtype:"BF16",shard,params:"6,144"};
  const postNorm: Weight={key:`language_model.model.layers.${layer}.post_attention_layernorm.weight`,shape:"[6144]",dtype:"BF16",shard,params:"6,144"};
  const routerGateWeights=router.weights.filter(weight=>weight.key.includes(".gate.weight"));
  return {
    input:cloneOp(packed,{id:"s-input",kind:"io",title:"Hidden states",input:"Xₗ",inputShape:"[B,S,6144]",output:"residual + working copy",outputShape:"2 × [B,S,6144]",weights:[]}),
    position:cloneOp(attn,{id:"s-position",kind:"route",title:"Build Position IDs",kicker:"vLLM RUNTIME I/O",input:"num_computed_tokens + query offsets",inputShape:"[B] + [Nq]",output:"positions",outputShape:"[Nq]",formula:"position(req,i)=num_computed_tokens[req]+i",formulaNote:"positions 由 vLLM runner 在模型 forward 之前构造，再传给 MiniMax-M3 的 fused QKNorm + RoPE kernel。",source:"gpu_model_runner.py · _prepare_inputs",sourceUrl:RUNNER_URL,weights:[]}),
    attnmeta:cloneOp(attn,{id:"s-attnmeta",kind:"mask",title:"Build Attention Metadata",kicker:"vLLM RUNTIME I/O",input:"query_start_loc, seq_lens, causal=True",inputShape:"[B+1] · [B] · bool",output:"implicit causal / padding layout",outputShape:"backend metadata; 非稠密 [S,T]",formula:"valid(req,q,k)=(k<seq_len[req]) ∧ (k≤context_len[req]+q)",formulaNote:"同一份边界元数据同时约束 indexer 的 block selection 和 main sparse attention。",source:"gpu_model_runner.py · CommonAttentionMetadata",sourceUrl:RUNNER_URL,weights:[]}),
    slots:cloneOp(attn,{id:"s-slots",kind:"route",title:"Resolve KV Slots",kicker:"vLLM RUNTIME I/O",input:"positions + block_table",inputShape:"[Nq] + [B,Nblocks]",output:"slot_mapping + block_table",outputShape:"[Nq] + [B,Nblocks]",formula:"slot=block_table[req,⌊position/block_size⌋]·block_size+(position mod block_size)",formulaNote:"slot_mapping 用于 K/V 写入；block_table 把 indexer 选出的逻辑 block id 翻译为物理 page。",source:"gpu_model_runner.py · compute_slot_mapping",sourceUrl:RUNNER_URL,weights:[]}),
    norm:cloneOp(normBase,{id:"s-norm",kind:"norm",title:"Gemma RMSNorm",source:"nvidia/model.py · MiniMAXGemmaRMSNorm.forward · L130–142",sourceUrl:NORM_FORWARD_URL,weights:[inputNorm]}),
    packed:cloneOp(packed,{id:"s-packed",kind:"linear",title:"QKV + Index Projection",summary:"一次 column-parallel GEMM 同时产生 Q、K、V、Qidx、Kidx；vLLM 将五段结果保存在同一个 packed tensor 中。",formulaNote:"这是五路线性投影节点，不执行 Q/K Norm、RoPE、KV cache 写入或 Attention。",runtime:"vLLM: MinimaxM3QKVParallelLinearWithIndexer · packed [q|k|v|index_q|index_k]",codeSections:QKV_INDEX_PROJECTION_SECTIONS,codeSymbols:QKV_INDEX_PROJECTION_SYMBOLS}),
    split:cloneOp(packed,{id:"s-split",kind:"split",title:"Split 5 outputs",input:"packed projection",inputShape:"[B,S,9856]",output:"Q/K/V · Qidx/Kidx",outputShape:"8192/512/512 · 512/128",formula:"split(x,[8192,512,512,512,128],dim=-1)",weights:[]}),
    idxnorm:cloneOp(indexer,{id:"s-idxnorm",kind:"norm",title:"Index Q/K Gemma RMSNorm + RoPE",summary:"分别对 Qidx/Kidx 执行 Gemma 风格 RMSNorm，再用同一组 position embeddings 旋转；Qidxᵣ 直接进入打分，Kidxᵣ 写入独立 Index K cache。",input:"Qidx,Kidx + position embeddings",inputShape:"[B,S,4,128] · [B,T,1,128]",output:"Index Q query · current Index K",outputShape:"[B,4,S,128] · [B,S,128]",weights:indexer.weights}),
    idxcache:cloneOp(indexer,{id:"s-idxcache",kind:"cache",title:"Index K Cache · key-only",summary:"vLLM 为 Indexer 单独分配 side cache：每 token 只保存一个 128 维 Index K，不保存 Index V，也不与主 Paged KV Cache 混用。",input:"current Index K + index slot_mapping",inputShape:"[B,S,128] + [Nq]",output:"cached Index K history",outputShape:"key-only pages · [T,128]",formulaNote:"MiniMaxM3IndexerCache 使用独立 prefix 注册到 KV-cache manager；Indexer score kernel 通过 self.index_cache.kv_cache 读取历史 Index K。",runtime:"vLLM: MiniMaxM3IndexerCache · bf16/fp8_e4m3",source:"common/indexer.py · MiniMaxM3IndexerCache",sourceUrl:`${VLLM_INDEXER_URL}#L101-L151`,weights:[]}),
    idxscore:cloneOp(indexer,{id:"s-idxscore",kind:"matmul",title:"Index Q × cached Kᵀ",input:"Index Q query + cached Index K",inputShape:"[B,max(1,4/TP),S,128] · [B,T,128]",output:"Index token scores",outputShape:"[B,max(1,4/TP),S,T]",formulaNote:"这里只做 Index Q 与完整 Index K history 的点积；不缩放，也不在这个节点混入 causal mask。",weights:[]}),
    idxmask:cloneOp(indexer,{id:"s-idxmask",kind:"mask",title:"Mask Future Index Keys",summary:"在 block max 之前把未来 key 和补齐槽设为 −∞，防止不可见 token 影响选块。",input:"Index token scores + position_ids",inputShape:"[B,max(1,4/TP),S,T] + [B,S]",output:"causal Index scores",outputShape:"[B,max(1,4/TP),S,T]",weights:[]}),
    blockmax:cloneOp(indexer,{id:"s-blockmax",kind:"route",title:"Block Max · B_block keys",input:"causal Index scores",inputShape:"[B,N_idx/TP,S,T]",output:"block scores",outputShape:"[B,N_idx/TP,S,⌈T/B_block⌉]",formulaNote:"每 B_block=128 个 key 的 Index score 取最大值，得到一个 block score。",weights:[]}),
    topk:cloneOp(topk,{id:"s-topk",kind:"route",title:"Top-K_block Blocks · per group",input:"block scores + local block priority",inputShape:"[B,N_idx/TP,S,N_blocks]",output:"block_indices",outputShape:"[B,N_idx,S,K_block]",formulaNote:"K_block=16；每个 query、每个 Index/KV group 独立选择逻辑 blocks，local block 以 +∞ 保证入选，无效槽记为 −1。"}),
    mainnorm:cloneOp(attn,{id:"s-mainnorm",kind:"norm",title:"Main Q/K Gemma RMSNorm",summary:"分别对主 Attention 的每个 Q/K head 执行 Gemma 风格 RMSNorm。",input:"Q,K",inputShape:"[B,64,S,128] · [B,4,T,128]",output:"Q̃,K̃",outputShape:"same",weights:attn.weights.filter(w=>w.key.includes("_norm"))}),
    rope:cloneOp(attn,{id:"s-rope",kind:"rope",title:"Partial RoPE",input:"Q̃,K̃ + positions",inputShape:"Q/K + [S]",output:"Qᵣ,Kᵣ",outputShape:"Q/K unchanged",weights:[]}),
    cache:cloneOp(attn,{id:"s-cache",kind:"cache",title:"Paged KV Cache",input:"Kᵣ,V + block table",inputShape:"KV pages + [B,Nblocks]",output:"paged K,V",outputShape:"[Npages,128,4,128] ×2",formula:"physical_page=block_table[logical_block]",weights:[]}),
    qk:cloneOp(attn,{id:"s-qk",kind:"matmul",title:"Q × paged Kᵀ · Top-K_block",input:"Qᵣ + paged K + block_indices",inputShape:"[B,Nₕ/TP,S,Dₕ] + KV pages + [B,N_idx,S,K_block]",output:"local sparse scores",outputShape:"[B,Nₕ/TP,S,K_sel]",formulaNote:"没有独立的 KV-view 映射算子：paged-attention kernel 根据 block_indices 与 block_table 直接读取对应 K pages。",weights:[]}),
    scale:cloneOp(attn,{id:"s-scale",kind:"scale",title:"Scale 1/√Dₕ",input:"scores",inputShape:"[B,Nₕ/TP,S,K_sel]",output:"scaled scores",outputShape:"same",weights:[]}),
    mask:cloneOp(attn,{id:"s-mask",kind:"mask",title:"Apply Token Causal / Pad Mask",summary:"在 Top-16 候选 blocks 内继续排除未来 token 与 padding；选块范围和 token 可见性是两层不同约束。",input:"selected scores + token bounds",inputShape:"[B,64/TP,S,Ksel] + runtime metadata",output:"masked selected scores",outputShape:"[B,64/TP,S,Ksel]",formula:"Aᵢⱼ←valid_token(i,j) ? Aᵢⱼ : −∞",formulaNote:"Transformers eager/SDPA 会先把 block_indices 展开为 block_keep，再与 attention_mask 合并；部署 kernel 可直接消费 block indices 与边界元数据。",weights:[]}),
    softmax:cloneOp(attn,{id:"s-softmax",kind:"softmax",title:"Softmax",input:"masked scores",inputShape:"[B,64/TP,S,≤2048]",output:"probabilities",outputShape:"same",weights:[]}),
    pv:cloneOp(attn,{id:"s-pv",kind:"matmul",title:"P × paged V · same Top-K_block",input:"P + paged V",inputShape:"[B,Nₕ/TP,S,K_sel] + KV pages",output:"local heads",outputShape:"[B,S,NₕDₕ/TP]",formulaNote:"kernel 按 Q×K 阶段相同的 block_indices 顺序直接读取 V pages；不物化 selected V 张量。",weights:[]}),
    oproj:cloneOp(attn,{id:"s-oproj",kind:"linear",title:"O Projection",input:"heads",inputShape:"[B,S,8192]",output:"Yattn",outputShape:"[B,S,6144]",weights:attn.weights.filter(w=>w.key.includes("o_proj"))}),
    addattn:cloneOp(combine,{id:"s-addattn",kind:"add",kicker:"DECODER LAYER · ATTENTION RESIDUAL",title:"Attention Residual Merge",summary:"在 Decoder Layer 内把 Sparse Attention 分支 Yattn 加入 residual stream Xₗ，得到更新后的 U；图中将 fused add 与紧随其后的 post-norm 分开表达。",input:"Xₗ + Yattn",inputShape:"2 × [B,S,6144]",output:"U · updated residual stream",outputShape:"[B,S,6144]",formula:"U=Xₗ+Yattn",formulaNote:"实际调用位于 DecoderLayer.forward L773：fused kernel 先执行 residual += hidden_states，再对更新后的 residual 执行 post-attention Gemma RMSNorm。",runtime:"fused_allreduce_gemma_rms_norm · attention residual",source:"nvidia/model.py · MiniMaxM3DecoderLayer.forward · L773–775",sourceUrl:`${CODE_URL}#L773-L775`,weights:[]}),
    postnorm:cloneOp(normBase,{id:"s-postnorm",kind:"norm",title:"Post-attn Gemma RMSNorm",summary:"输入 U 已由上游 Add 节点计算完成；此节点只执行 Gemma RMSNorm(U)，输出唯一的 Û 作为 MoE 输入。",formulaNote:"U 是上游 Add 的单一输出；本节点只计算 RMS(U) 与 (1+γpost) 缩放，不重复执行 residual add。",input:"U",inputShape:"[B,S,6144]",output:"Û",outputShape:"[B,S,6144]",source:"nvidia/model.py · MiniMAXGemmaRMSNorm.forward · L130–142",sourceUrl:NORM_FORWARD_URL,weights:[postNorm]}),
    router:cloneOp(router,{id:"s-router",kind:"route",kicker:"FP32 ROUTER · 128 LOGITS",title:"FP32 Router Logits",summary:"每个 token 通过 GateLinear 计算 128 个 FP32 router_logits；本节点不执行 sigmoid、Top-4 或专家计算。",input:"Û",inputShape:"[B,S,6144]",output:"router_logits",outputShape:"[B,S,128]",formula:"router_logits=ÛWrouterᵀ",formulaNote:"这是 Python 层唯一显式产生的 Router 输出；下游 FusedMoE 才执行 sigmoid、correction bias、Top-4 与混合权重计算。",runtime:"GateLinear · FP32",weights:routerGateWeights}),
    experts:cloneOp(experts,{id:"s-experts",kind:"activation",kicker:"FUSED ROUTING · TOP-4 EXPERTS",title:"Fused Top-4 Routing + Experts",summary:"FusedMoE 消费 router_logits，在内部完成 sigmoid、correction bias、Top-4、归一化混合权重和 4 个专家计算。",input:"Û + router_logits",inputShape:"[B,S,6144] + [B,S,128]",output:"weighted routed output",outputShape:"[B,S,6144]",formulaNote:"先用 σ(r) 得到路由分数 s；s+b 只用于挑选 Top-4，混合权重仍取未加 bias 的 s，归一化后乘 routed_scaling_factor，最后对 4 个专家输出加权求和。expert ids 与 router weights 都是 fused kernel 内部量。",weights:experts.weights}),
    shared:cloneOp(shared,{id:"s-shared",kind:"activation",title:"Shared Expert ×1",input:"Û",inputShape:"[B,S,6144]"}),
    sum:cloneOp(combine,{id:"s-sum",kind:"add",title:"Add Routed + Shared",summary:"把路由专家分支的 Y_routed 与共享专家分支的 Y_shared 逐元素相加。",input:"Y_routed + Y_shared",inputShape:"2 × [B,S,6144]",output:"Ymoe",outputShape:"[B,S,6144]",weights:[]}),
    addout:cloneOp(combine,{id:"s-addout",kind:"add",kicker:"DECODER LAYER · MOE RESIDUAL",title:"Decoder Layer Residual Merge",summary:"在 Decoder Layer 边界把 MoE 分支 Ymoe 与 residual stream U 逻辑合并，得到 Xₗ₊₁；该 merge 延迟融合到下一层 input RMSNorm。",input:"U + Ymoe",inputShape:"2 × [B,S,6144]",output:"Xₗ₊₁ · logical next-layer input",outputShape:"[B,S,6144]",formula:"Xₗ₊₁=U+Ymoe",formulaNote:"当前层 L776–778 返回 Ymoe 与 U 两条独立流；下一 Decoder Layer 在 L758–767 的 fused input RMSNorm 中执行实际 add。",runtime:"MiniMaxM3DecoderLayer boundary · deferred residual merge",source:"nvidia/model.py · MiniMaxM3DecoderLayer.forward · L758–778",sourceUrl:`${CODE_URL}#L758-L778`,weights:[]}),
  };
}
